- .gitignore
- app/src/main/java/org/sopt/app/application/alert/AlertService.java
- app/src/main/java/org/sopt/app/application/alert/AlertUseCase.java
- app/src/main/java/org/sopt/app/application/alert/SendAlertUseCase.java
- app/src/main/java/org/sopt/app/application/alert/command/SaveAlertCommand.java
- app/src/main/java/org/sopt/app/application/notice/NoticeService.java
- app/src/main/java/org/sopt/app/common/exception/UserNotFoundException.java
- app/src/main/java/org/sopt/app/domain/entity/Alert.java
- app/src/main/java/org/sopt/app/domain/entity/User.java
- app/src/main/java/org/sopt/app/domain/enums/OsType.java
- app/src/main/java/org/sopt/app/interfaces/alert/AlertRepository.java
- app/src/main/java/org/sopt/app/interfaces/postgres/NoticeRepository.java
- app/src/main/java/org/sopt/app/interfaces/postgres/UserJpaRepository.java
- app/src/main/java/org/sopt/app/interfaces/postgres/alert/AlertRepository.java
- app/src/main/java/org/sopt/app/presentation/alert/AlertController.java
- app/src/main/java/org/sopt/app/presentation/alert/dto/PartResponseDTO.java
- app/src/main/java/org/sopt/app/presentation/alert/dto/SavePartsDTO.java
1. 이메일 인증 완료 이후 알림받을 파트 정보 저장하는 로직을 추가
- 파트 선택 후 팝업창에서 알림설정을 하지 않더라도 API 에서 active: false로 데이터 받도록 수정
- 추후 마이페이지에서 알림 설정 용이하게 하기 위함
2. gitignore에 .idea 추가
3. User, Alert 테이블 수정
- Long으로 타입 변경
- Alert 테이블에 active 값 추가(os 알림설정 여부)
- User 정보에 email 추가
** 추후에 기존 db의 user table 볼 수 있으면 좋은데, 협의 필요
> [Feat] 사용자 알림정보 저장

- src/main/java/org/sopt/app/application/stamp/StampService.java
- src/main/java/org/sopt/app/common/ResponseCode.java
- src/main/java/org/sopt/app/common/exception/ApiExceptionHandler.java
- src/main/java/org/sopt/app/presentation/stamp/StampController.java
스탬프 등록시 중복 등록되는 현상을 방지하기 위하여
userId, missioinId로 Stamp 테이블 조회 후 이미 있는 데이터라면 
400 BadRequest 로 ApiException 을 던진다.
> [Fix] 스탬프 등록시 중복 등록 방지

- src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
- src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
- src/main/java/org/sopt/app/domain/enums/UserStatus.java
- src/main/java/org/sopt/app/presentation/auth/AuthResponse.java
- src/main/java/org/sopt/app/presentation/config/ConfigController.java
- src/main/java/org/sopt/app/presentation/config/ConfigResponse.java
- src/main/java/org/sopt/app/presentation/user/UserController.java
- src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
- src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
앱 메인 뷰 클라 작업을 위해 플레이그라운드 먼저 연동했습니다!
앱 메인 뷰 작업에 필요한 분기 데이터와 활동 기수 데이터를 생성하고, 분기 데이터를 조회하는 API를 작성했습니다.
앱 메인 뷰 API에 스프린트 1 이내에 운영팀으로부터 출석점수 조회 API를 제공받은 뒤 한 차례 수정이 있을 예정이며, 현재 더미 데이터를 제공 중입니다.
추가로 간단한 API 엔드포인트 변경이 있었습니다.
feature/userOriginal
#51
> feat: 앱 메인 뷰

- src/main/java/org/sopt/app/application/auth/JwtTokenService.java
- src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
- src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/common/config/JwtAuthenticationFilter.java
- src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
- src/main/java/org/sopt/app/common/exception/BaseException.java
- src/main/java/org/sopt/app/common/exception/UnauthorizedException.java
- src/main/java/org/sopt/app/common/response/CommonControllerAdvice.java
- src/main/java/org/sopt/app/common/response/CommonResponse.java
- src/main/java/org/sopt/app/common/response/ErrorCode.java
- src/main/java/org/sopt/app/presentation/auth/AuthController.java
- src/main/java/org/sopt/app/presentation/auth/AuthRequest.java
- src/main/java/org/sopt/app/presentation/auth/AuthResponse.java
- src/main/java/org/sopt/app/presentation/auth/AuthResponseMapper.java
- src/main/java/org/sopt/app/presentation/user/UserController.java
API 1차 배포 이후, 클라이언트와 운영팀 요구사항을 반영하였습니다.
아래 요구사항을 진행하려면 플그에서 활동 기수와 유저 아이디를 얻어 오는 작업이 필요하여, 플그 토큰을 리프레시하는 로직까지 함께 작업하게 되었습니다!
플레이그라운드 측에 토큰 교환을 요청했으나 실패한 경우 401을 뱉어 앱에서 플그 재로그인을 요청할 예정입니다.
추가로 현재 코드에는 에러 처리 방식이 혼용 되고 있으나 추후 하나로 통일하는 작업을 거칠 예정입니다!
지금은 조금 난잡해도 너그러이 봐주시면 감사하겠습니당
앱팀 요구사항
- 로그인 시 분기 처리 위한 활동 기수 여부 추가
- 닉네임 중복 검사 로직 API로 분리
- rT 한 달로 연장
운영팀 요구사항
- 토큰에 플레이그라운드 아이디 추가
feature/requirements
#53
> feature: 클라, 운영팀 요구사항 반영

- src/main/java/org/sopt/app/application/auth/JwtTokenService.java
refresh decode 시 에러 핸들링 추가
hotfix/jwt-error-handle
#139
> fix: refresh decode 시 에러 핸들링 추가

- src/main/java/org/sopt/app/application/notification/NotificationService.java
- src/main/java/org/sopt/app/interfaces/postgres/NotificationRepository.java
- src/main/java/org/sopt/app/presentation/notification/NotificationController.java
- src/main/java/org/sopt/app/presentation/notification/NotificationResponse.java
- (신버전) 알림 상세 조회 URI : `/detail/{notificationId}` 로 변경
- (신버전) 알림 리스트 조회 URI : `/all` 로 변경
- (신버전) 알림 읽음 처리 URI : `/read` (전체), `/read/{notificationId}` (개별) 로 변경
feat/#148-create-legacy-alarm-api
#148
> FIX : 이전 버전 알림 API 재생성 및 Deprecated 처리

- src/main/java/org/sopt/app/application/auth/PlaygroundAuthInfo.java
memberProfile에 jsonMapping이 빠져있어 null이 되는 현상 수정
fix/playground-memberprofile
> fix: pg memberProfile dto json 매핑 수정

- src/main/java/org/sopt/app/application/poke/FriendService.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
> fix: 날 찌른 친구 불러오는 로직 수정

- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/presentation/poke/PokeController.java
friendList response에 들어가는 각 친구 목록 당 size가 단순하게 2개로 자른 사이즈로 들어가던 문제 수정.
> fix: FriendList size 정상적으로 수정

- src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/presentation/poke/PokeController.java
온보딩 뷰에서 랜덤 유저를 추천할 때 이미 찌른 경우를 나타낼 수 있도록 로직을 수정했습니다.
단순 반복보다 해시 맵이 더 접근성이 좋을 거 같아 해시 맵을 사용했습니다.
fix/random-user-isAlreadyPoke
> fix: 온보딩 유저 추천 - 찌르기 여부 수정

- src/main/java/org/sopt/app/facade/PokeFacade.java
친구가 아닌 유저 아이디로만 Shuffle 하도록 로직 추가
`feat/onboarding-exclude-friend`
> FEAT : 친구가 아닌 유저 아이디로만 Shuffle 하도록 로직 추가

- src/main/java/org/sopt/app/AppApplication.java
- src/main/java/org/sopt/app/application/fortune/FortuneEvent.java
- src/main/java/org/sopt/app/application/fortune/FortuneEventListener.java
- src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
- src/main/java/org/sopt/app/application/notification/NotificationService.java
- src/main/java/org/sopt/app/application/poke/PokeEventListener.java
- src/main/java/org/sopt/app/common/utils/HttpHeadersUtils.java
- src/main/java/org/sopt/app/presentation/fortune/FortuneAlarmRequest.java
- src/main/java/org/sopt/app/presentation/notification/NotificationRequest.java
- 로직을 천천히 살펴보다가 FCM 기반 작동이 event로 이루어지는것인지 notification service를 통해 이루어지는 것인지 확인이 불가능하여 일단 확인해본 notification service를 통해서 전체 알림 생성만 해두는 크론탭 기반 scheduler로 구현하였습니다! 
```java
public class FortuneScheduler {
private final NotificationService notificationService;
// 매일 아침 9시에 실행되는 스케줄러
@Scheduled(cron = "0 0 9 * * ?")
public void runDailyFortuneCreation() {
NotificationRequest.RegisterNotificationRequest registerNotificationRequest = createFortuneNotificationRequest();
notificationService.registerNotification(registerNotificationRequest);
}
private NotificationRequest.RegisterNotificationRequest createFortuneNotificationRequest() {
return NotificationRequest.RegisterNotificationRequest.builder()
.notificationId(UUID.randomUUID().toString())  // 고유한 알림 ID
.title("오늘의 솝마디")  // 알림 제목 …
```
> [FEAT] 오늘의 솝마디 스케쥴러 구현 - #344

- src/main/java/org/sopt/app/application/friend/FriendFilter.java
- src/main/java/org/sopt/app/application/friend/FriendRecommender.java
- src/main/java/org/sopt/app/application/friend/FriendService.java
- src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserFindConditionCreatorFactory.java
- src/main/java/org/sopt/app/application/playground/user_finder/PlaygroundUserIdsProvider.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/test/java/org/sopt/app/application/FriendRecommenderTest.java
- src/test/java/org/sopt/app/application/PlaygroundUserIdsProviderTest.java
- src/test/java/org/sopt/app/facade/PokeFacadeTest.java
친구 추천에 대한 테스트를 추가하였습니다.
친구 추천에 대한 책임을 PokeFacade에서 새로운 객체를 만들어 위임했습니다.
기존 Friend filter에서 userId를 필터링 해야하지만, playground id를 필터링하고 있던 오류를 해결했습니다.
closed #346
> [FEAT] 친구 추천 테스트 추가

- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/application/poke/PokeService.java
- src/main/java/org/sopt/app/domain/entity/Friend.java
- src/main/java/org/sopt/app/domain/entity/poke/PokeHistory.java
- src/main/java/org/sopt/app/domain/entity/poke/PokeMessage.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- 다음과 같은 문제점 
- 1. entity 영속화 되지 않은 시점에서 id값 호출
- 2. null check인 @NotNull 사용 
- @NotNull을 붙인채로 builder로 생성시에 객체 자체에 id값이 없어 어플리케이션단에서 오류 발생 
closed #366 
-
> [FIX] 콕찌르기 무한반복 에러 수정 - #366

- src/main/java/org/sopt/app/interfaces/postgres/fortune/FortuneCardRepositoryImpl.java
FortuneWord가 아닌 FortuneCard id를 가져오는 로직을 수정했습니다.
> [HOTFIX] FortuneWord가 아닌 FortuneCard id를 가져오는 로직 수정

- src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
- src/main/java/org/sopt/app/common/config/LazyDataSourceConfiguration.java
출처: https://mangkyu.tistory.com/391 [MangKyu's Diary:티스토리]
closed #375 
-
> [REFACTOR] 웹링크 null로 변경 - #375

- src/main/java/org/sopt/app/application/slack/SlackService.java
- src/main/java/org/sopt/app/common/response/CommonControllerAdvice.java
- src/main/java/org/sopt/app/common/response/ExceptionWrapper.java
- src/main/java/org/sopt/app/common/response/GlobalExceptionHandler.java
- src/main/java/org/sopt/app/common/response/SlackLogger.java
- src/main/java/org/sopt/app/common/response/SlackLoggerAspect.java
- src/main/java/org/sopt/app/common/response/SlackMessageGenerator.java
- src/test/java/org/sopt/app/application/SlackServiceTest.java
- AOP 구현
- 1. 실제 어노테이션이 하는일 구현된 클래스
- 2. HTTP request와 UserId를 잡아내어 MessageGenerator로 Slack 메세지 생성
- ```java
@Aspect
@Component
@Slf4j
@RequiredArgsConstructor
public class SlackLoggerAspect {
private final HttpServletRequest request;
private final SlackService slackServic;
private Long getUserId() {
Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
val user = (User) authentication.getPrincipal();
return user.getId();
}
@Before(value = "@annotation(org.sopt.app.common.response.SlackLogger)")
public void sendLogForError(final JoinPoint joinPoint) {
Object[] args = joinPoint.getArgs();
if (args.length != 1) {
log.warn("Slack Logger Failed : Invalid Used");
return;
}
if (args[0] instanceof Exception) {
String requestUrl = request.getRequestURI();  // 요청 …
```
> [REFACTOR] slack 알림 서비스 refactoring - #382

- src/main/java/org/sopt/app/application/rank/PartScores.java
- src/main/java/org/sopt/app/application/rank/SoptampPartRankCalculator.java
- src/main/java/org/sopt/app/domain/enums/Part.java
PartScores를 일급 컬렉션을 사용한 로직으로 수정하였습니다.
closed #394
> [CHORE] PartScores 일급 컬렉션을 사용한 로직 수정

- src/main/java/org/sopt/app/application/friend/FriendRecommender.java
- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
- src/main/java/org/sopt/app/domain/enums/PlaygroundPart.java
- src/main/java/org/sopt/app/facade/AuthFacade.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
솝탬프 닉네임 생성에 오류가 있는 부분을 수정하였습니다.
closed #421 
- postman 테스트 완료했습니다.
- 이렇다면 회장, 부회장, 총무, 운팀장, 미팀장, 메팀장은 솝탬프에 참여하더라도 파트별 랭킹에 관여가 불가합니다 (원래 불가능했어요)
- "~~파트장"이 나을까요 "~~팟장"이 나을까요?
> [FIX] 솝탬프 닉네임 설정 오류 수정

- src/main/java/org/sopt/app/application/notification/NotificationService.java
- src/main/java/org/sopt/app/interfaces/postgres/NotificationRepository.java
- src/main/java/org/sopt/app/presentation/notification/NotificationController.java
알림 목록의 카테고리 별 조회 기능을 추가하였습니다.
param에 category 필드를 추가하여 category 필드가 없다면 전체 알림 목록 조회, category 필드가 있다면 카테고리 별 알림 목록 조회가 가능하도록 기능을 구현했습니다.
closed #430 
- Postman 테스트 완료했습니다.
> [FEAT] 알림 목록 카테고리 별 조회 기능 추가

- src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
- src/main/java/org/sopt/app/presentation/calendar/CalendarResponse.java
일정이 끝났을 때, 일정 관련 api에서 가장 마지막 일정을 반환하도록 수정합니다.
closed #444 
- postman 테스트도 완료했습니다.
> [MODIFY] 일정이 끝났을 때, 일정 관련 api에서 가장 마지막 일정을 반환하도록 수정

- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/application/playground/dto/PlayGroundEmploymentResponse.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- src/main/java/org/sopt/app/presentation/home/response/EmploymentPostResponse.java
closed #436 
- swagger test 완료
> [FEAT] 플레이그라운드 채용정보 조회 기능 API  -  #436

- src/main/java/org/sopt/app/application/meeting/MeetingCategory.java
- src/main/java/org/sopt/app/application/meeting/MeetingResponse.java
- src/main/java/org/sopt/app/application/meeting/MeetingStatus.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
전체 모임 확인 dummy api를 추가하였습니다.
크루에게 internal api 전달받으면 작업 시작하도록 하겠습니다.
closed #431
> [FEAT] 전체 모임 확인 dummy api 추가

- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/application/playground/dto/PlayGroundPostCategory.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- src/main/java/org/sopt/app/presentation/home/response/RecentPostsResponse.java
closed #434 
- Playground에 content값을 추가해서 요청했습니다
- 아직 값이 없어 content는 null인 상태입니다.
> [FEAT] 카테고리별 최신 게시물 조회 API 구현 - #434

- src/main/java/org/sopt/app/application/stamp/StampService.java
- src/main/java/org/sopt/app/presentation/stamp/StampRequest.java
스탬프 contents가 empty이면 오류가 발생하는 에러를 해결했습니다.
contents가 empty인 스탬프 확인시 에러가 아닌 로그를 남기도록 수정하였습니다.
closed #441
> [FIX] 솝탬프 contents가 empty이면 오류가 발생하는 에러 해결

- src/main/java/org/sopt/app/application/app_service/AppServiceBadgeService.java
- src/main/java/org/sopt/app/application/app_service/AppServiceName.java
- src/main/java/org/sopt/app/application/app_service/FortuneBadgeManager.java
- src/main/java/org/sopt/app/application/app_service/PokeBadgeManager.java
- src/main/java/org/sopt/app/application/app_service/SoptampBadgeManager.java
- src/main/java/org/sopt/app/application/app_service/dto/AppServiceBadgeInfo.java
- src/main/java/org/sopt/app/application/app_service/dto/AppServiceEntryStatusResponse.java
- src/main/java/org/sopt/app/application/app_service/dto/AppServiceInfo.java
- src/main/java/org/sopt/app/domain/entity/AppService.java
기획 변경으로 인해 앱 서비스 반환 API를 수정하였습니다.
closed #456 
- App Service 엔티티 변경으로 인한 App Service에 컬럼 추가해두었습니다.
> [MODIFY] 기획 변경으로 인한 앱 서비스 반환 API 수정

- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/application/playground/dto/PlayGroundPostDetailResponse.java
- src/main/java/org/sopt/app/application/playground/dto/PostWithMemberInfo.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- src/main/java/org/sopt/app/presentation/home/response/EmploymentPostResponse.java
- src/main/java/org/sopt/app/presentation/home/response/RecentPostsResponse.java
closed #434 
- 플레이그라운드 게시물 반환 기능 
- 채용 정보 조회
> [REFACTOR] 플레이그라운드 게시물 반환 기능 + 채용 정보 조회 사용자 정보 추가 - #434

- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/application/playground/dto/PlayGroundCoffeeChatResponse.java
- src/main/java/org/sopt/app/application/playground/dto/PlayGroundCoffeeChatWrapper.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- src/main/java/org/sopt/app/presentation/home/response/CoffeeChatResponse.java
> [FEAT] 커피챗 등록 유저들 리스트 조회 API - #435

- src/main/java/org/sopt/app/application/meeting/CrewClient.java
- src/main/java/org/sopt/app/application/meeting/CrewMeetingResponse.java
- src/main/java/org/sopt/app/application/meeting/MeetingCategory.java
- src/main/java/org/sopt/app/application/meeting/MeetingResponse.java
- src/main/java/org/sopt/app/application/meeting/MeetingService.java
- src/main/java/org/sopt/app/application/meeting/MeetingStatus.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/common/config/ClientConfig.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- src/main/java/org/sopt/app/presentation/home/MeetingParamRequest.java
- src/main/java/org/sopt/app/presentation/home/response/HomeDescriptionResponse.java
기존 Dummy api로 구현되어 있던 모든 모임 조회 api를 크루 api와 연결하였습니다.
closed #431 
- yml 파일에서 makers.crew.server를 추가해두었습니다! notion 설정 파일에 업데이트하고 github secret에도 dev, prod 업데이트 해두었습니다.
> [FEAT] 모든 모임 조회 api 크루 api와 연결

- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/application/playground/dto/PlayGroundUserSoptLevelResponse.java
- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
- src/main/java/org/sopt/app/application/poke/PokeService.java
- src/main/java/org/sopt/app/application/rank/SoptampUserRankCalculator.java
- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/domain/entity/Icons.java
- src/main/java/org/sopt/app/domain/enums/IconType.java
- src/main/java/org/sopt/app/facade/AuthFacade.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/facade/RankFacade.java
- src/main/java/org/sopt/app/interfaces/postgres/IconRepository.java
- src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
- src/main/java/org/sopt/app/presentation/user/UserController.java
- src/main/java/org/sopt/app/presentation/user/UserResponse.java
- src/test/java/org/sopt/app/facade/PokeFacadeTest.java
> [FEAT] 솝트 로그 API 개발  - #437

- src/main/java/org/sopt/app/application/rank/CachedUserInfo.java
- src/main/java/org/sopt/app/application/rank/RankCacheService.java
- src/main/java/org/sopt/app/application/rank/RankScheduler.java
- src/main/java/org/sopt/app/application/rank/RedisRankService.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserFinder.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
- src/main/java/org/sopt/app/common/config/CacheType.java
- src/main/java/org/sopt/app/common/config/RedisConfig.java
- src/main/java/org/sopt/app/facade/RankFacade.java
- src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
- src/test/java/org/sopt/app/facade/RankFacadeTest.java
Redis의 sorted set을 이용하여 솝탬프 랭킹을 캐싱하여 응답속도를 높혔습니다.
closed #472
> [REFACTOR] sorted set을 이용한 솝탬프 랭킹 캐싱

- script/deploy_container.sh
- script/health_check.sh
health check시에 마지막 retries까지 가서야 health check가 성공하는 문제가 있어 RETRIES 시간을 증가했습니다.
\+ docker-compose를 이용해 redis를 실행시키는 과정에서의 오류를 수정했습니다.
closed #491 
- 확인하시고 머지 부탁드릴게요!
- dev 환경 docker 무중단 배포 기능 적용완료했고, 테스트 완료했습니다.
> [MODIFY] health check시에 RETRIES 시간 증가

- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/presentation/home/response/RecentPostsResponse.java
- src/test/java/org/sopt/app/application/PlaygroundAuthServiceTest.java
- closes #504 
- RecentPostsResponse에 url 필드를 추가하면서 외부 Playground API로부터 받은 게시물 응답(PlaygroundPostResponse)에 URL을 직접 조립해 추가하는 방식으로 변경했습니다. url 생성은 기존의 convertPlaygroundWebPageUrl를 활용했습니다.
- 가독성과 책임분리를 위해 hot게시물 조회, 최근게시물 조회, 두 게시물 목록 합치기의 세 과정을 모두 담당하던 기존의 getRecentPosts에서 각 단계를 분리해 private 메소드들을 작성했습니다.
- 외부 api를 호출하는 특성상 local test 진행이 어려워 test code를 작성했습니다. test는 모두 통과했으니 dev 서버에서 테스트해보면 좋을 듯합니다!
> [FEAT] 플레이그라운드 카테고리별 게시물 조회 api에 url 추가 - #504

- src/main/java/org/sopt/app/presentation/user/UserController.java
- closes #513 
솝트로그 아이콘을 정렬했습니다. 
정렬 기준이 바뀔 경우를 대비해 정규 표현식을 사용해 정렬했습니다. 
https://github.com/sopt-makers/sopt-backend/blob/58a7652ff1ed5a0a23267cb89407de4cff41c8ce/src/main/java/org/sopt/app/presentation/user/UserController.java#L121-L125
> [Fix] 솝트로그 아이콘 정렬 추가 (#513)

- src/main/java/org/sopt/app/facade/AuthFacade.java
- closes #516 
솝트로그 조회 시 간헐적으로 솝탬프 관련 오류가 뜨는 것을 확인했어요.
```
2025-03-28T13:39:40.122Z ERROR 1 --- [app-server] [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: User not found] with root cause
java.lang.IllegalArgumentException: User not found
at org.sopt.app.application.rank.SoptampUserRankCalculator.lambda$getUserRank$3(SoptampUserRankCalculator.java:34) ~[!/:0.0.1-SNAPSHOT]
at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
at org.sopt.app.application.rank.SoptampUserRankCalculator.getUserRank(SoptampUserRankCalculator.java:34) ~[!/:0.0.1-SNAPSHOT]
at …
```
> [Fix] 플그로 로그인 시 soptamp 관련 로직 무조건 통과하도록 변경 및 테스트용 로그 삭제 (#516)

- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
- src/main/java/org/sopt/app/presentation/user/UserController.java
- closes #519 
솝트로그가 일부 유저에게 안 열리는 이슈를 해결합니다.
- 솝트로그 조회 시, 플그에서 받아온 정보를 바탕으로 기수와 파트를 `split()`으로 꺼내옵니다. 
해당 과정에서, 데이터가 어떻게 오는지는 확인하지 못했지만, 아래의 로그를 확인했습니다.
```
2025-03-30T17:58:58.229+09:00 ERROR 2500635 --- [app-server] [nio-8080-exec-4] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1] with root cause
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.sopt.app.application.playground.dto.PlaygroundProfileInfo$ActivityCardinalInfo.getPlaygroundPart(PlaygroundProfileInfo.java:124) ~[!/:0.0.1-SNAPSHOT]
at org.sopt.app.presentation.user.UserResponse$SoptLog.lambda$of$0(UserRe …
```
> [Fix] 솝트로그 관련 이슈 해결 (#519)

- src/main/java/org/sopt/app/presentation/user/UserResponse.java
- closes #521 
솝탬프 일시 중단으로 인해 "공개 예정!" 이라는 문자열이 내려오도록 수정했어요.
https://github.com/sopt-makers/sopt-backend/blob/aedf20f825349540f734dc1b4dc988cc2794e993/src/main/java/org/sopt/app/presentation/user/UserResponse.java#L173
> [Fix] 솝탬프 랭크 null인 경우 문자열 처리

- src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
- src/main/java/org/sopt/app/application/fortune/FortuneService.java
- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/common/utils/ActivityDurationCalculator.java
- src/main/java/org/sopt/app/common/utils/CurrentDate.java
- src/main/java/org/sopt/app/facade/AuthFacade.java
- closes #523 
- 최신 일정을 산정하는 기준이 CurrentDate.now였는데, 현재 날짜를 계산하는 CurrentDate class에서 now가 static final 필드여서 서버 시작 시점에 날짜가 고정돼있던 이슈를 발견했습니다. 그래서 동적으로 최신 날짜를 계산하도록 메소드화 시켰습니다.
0214dba900680256b38fb402cd79347f0a6e3d36
- 또한 전체 일정을 불러올 때는 시작일자 기준으로 정렬 후 시작일자가 동일한 일정은 종료일자를 기준으로 한번 더 정렬하게 되는데 최신 일정은 시작일자로만 정렬하고 있었기에 정렬 기준을 통일시켰습니다.
53779b500188716fbc182e420ab3040cea8d5265
- 하지만 이슈 리포트에서 날짜가 각각 4/3, 4/5로 다르게 불러와진 1차 세미나의 경우 디버깅했을 때 코드 상 이상이 없었고, 로컬에서 동일한 데이터셋으로 테스트했을 때에도 정상적으로 작동해서 redis cache 문제인 것으로 추정돼 prod, dev 서버에서 캘린더 캐시를 한번 정리했습니다.
- 현재 제 계정 기준으로는 정상적으로 날짜도 동일하게 조회되고 최신 일정도 1차 세미나로 불러와집니다. 유저별로 다른 최신 일정이 조회된 것은 CurrentDate 이슈, 날짜가 다르게 불러와진 것은 기존의 캐시에 4/3으로 기재된 이슈인 것으로 추정되나 우선 더 qa가 필요할 것 같습니다.
이외에 이전 pr의 리팩토링으로 더이상 사용하지 않게 된 메소드들을 삭제했습니다.
a6f7ae993318bc32d622bae5de26009c16113bfa …
> [FIX] 홈화면 최신 행사 일정 관련 이슈 - #523

- src/main/java/org/sopt/app/presentation/user/UserController.java
- src/main/java/org/sopt/app/presentation/user/UserResponse.java
- closes #527 
솝트로그 관련 이슈를 해결합니다.
- 명예오비 앱잼이나 프로젝트를 활동한 기수가 아닐 때 수행했을 시, 미상으로 파트 이름을 추출하도록 되어있어요. 
- 이를 솝트로그 API 응답에서 미상 값을 명시적으로 제거했어요.
https://github.com/sopt-makers/sopt-backend/blob/6c980c6c7d6233edf20f12606501af366a8feb8c/src/main/java/org/sopt/app/presentation/user/UserResponse.java#L176-L179
- 솝트로그 조회 시, `isActive` 를 판단하는 기준이 모호하여 오류가 있었어요.
- 기존에는 가장 최근의 Activity을 가져와서 현재 기수와 같으면 isActive로 판단했는데, 명예OB 앱잼의 경우도 활동 기수의 활동으로 플그에서 응답이 오기 때문에 이 경우를 filter로 제외하도록 했어요. 
https://github.com/sopt-makers/sopt-backend/blob/6c980c6c7d6233edf20f12606501af366a8feb8c/src/main/java/org/sopt/app/presentation/user/UserController.java#L111-L116
- 이제 솝탬프를 오픈해야 하므로, 솝트로그에서 솝탬프 등수를 다시 표시하도록 변경했어요.
- isActive가  reference 타입으로 지정되어 있어, `equals()` 비교가 아닌 `Boolean.TRUE.equals(isActive)` 로 안전하게 비교하도록 했어요. …
> [Fix] 솝트로그, 솝탬프 관련 이슈 해결 (#527)

- src/main/java/org/sopt/app/application/stamp/StampService.java
- src/main/java/org/sopt/app/common/exception/ForbiddenException.java
- src/main/java/org/sopt/app/common/response/ErrorCode.java
- src/main/java/org/sopt/app/domain/entity/soptamp/Stamp.java
- src/main/java/org/sopt/app/facade/SoptampFacade.java
- src/main/java/org/sopt/app/presentation/stamp/StampController.java
- src/main/java/org/sopt/app/presentation/stamp/StampRequest.java
- src/test/java/org/sopt/app/facade/SoptampFacadeTest.java
- closes #529 
1. 요청 DTO 구조 개선
- RegisterStampRequest, EditStampRequest의 공통 필드 추출 → BaseStampRequest 상속 구조로 리팩토링
389b8b655678a5a1a41c93d6f4d00c71b338cbe3
2. 유효성 검사 책임 분리
- 기존 StampService.validateStampInfo() 삭제
- 엔티티 내 Stamp.validate() 메서드로 유효성 검사 책임 이동
ddfc31f01e1f4a9509e964614275d8116de2e204
3. 권한 체크 로직 추가
- 기존에 스탬프 삭제 시 유저 본인의 스탬프인지 검증하지 않고 삭제가 이루어졌음
- 스탬프 삭제 시 userId vs stamp.userId 비교하여 권한 검증 추가
- 권한 없을 경우 ForbiddenException + STAMP_DELETE_FORBIDDEN 에러코드 반환
0f7590e1a2f7b46355fe3d6b476926629d68c67c
- 이에 맞춰 SoptampFacadeTest도 수정했습니다
2cf79b9c510346db7bf7cd3eecaca7d1027a9d65
5. 서비스 계층 의존성 정리
- StampController에서 stampService 직접 호출 제거
- 모든 비즈니스 로직은 SoptampFacade 통해 위임
- editStamp() 또한 Facade에서 수정 처리 로직 담당
75999492e721b1bca7e443ee74ea22a58a4b7b5d
스탬프 삭제 권한 미체크를 제외하면 솝탬프 로직 상 문제는 보이지 않아서 …
> [Refactor] 솝탬프 관련 로직 리팩토링 - #529

- .github/workflows/app-cd-dev.yml
- src/main/java/org/sopt/app/common/config/AwsConfig.java
- closes #548 
AWS Credential을 yml에서 주입하여 설정하는 기존 방식을 사용하고 있던 것을 발견했어요.
S3 관련 Access Denied 이슈를 발견하고, 수정하려고 하는데 액세스 키 값이 Github Secret과 yml에 둘 다 설정되어있고 둘의 일치 여부를 확인할 수 없어 디버깅이 어려웠어요.
이에, docker-compose로 배포 시에 `.env` 파일을 생성하고, 환경 변수를 Github Secret에서 동적으로 CD에서 주입한 뒤 AWS SDK가 기본 자격 증명 공급자 체인 (Default Credential Provider Chain)을 사용하도록 했어요.
작업 내용은 다음과 같아요.
1. AwsConfig에서 `@Value` 로 yml 값을 주입받던 코드 삭제 
```java
@Configuration
public class AwsConfig {
@Value("${cloud.aws.region.static}")
private String region;
@Bean
public AmazonS3 amazonS3() {
return AmazonS3ClientBuilder.standard()
.withRegion(region)
.build();
}
}
```
2. `.env` 파일을 동적으로 생성하고, AWS SDK가 자동으로 감지하도록 배포 스크립트 수정
```bash
- name: Docker Container Run
uses: appleboy/ssh-action@master
with:
username: ec2-user
host: ${{ …
```
> [Fix] AWS Credential 시크릿에서 주입받아 배포하도록 수정 (#548)

- build.gradle
- src/main/java/org/sopt/app/application/auth/JwtTokenService.java
- src/main/java/org/sopt/app/application/s3/S3Service.java
- src/main/java/org/sopt/app/common/config/AwsConfig.java
- src/test/java/org/sopt/app/application/S3ServiceTest.java
- closes #548
기존에 `spring-cloud-starter-aws` (AWS SDK v1 기반)를 사용하고, AWS 자격 증명을 `application.yml`에서 `@Value`로 주입받아 설정하는 방식을 사용하고 있었어요.
이 상황에서 자동 AWS 자격 증명 메커니즘을 사용하도록 변경하니, 오래된 `spring-cloud-starter-aws`가 의존하는 Jackson 라이브러리 버전과, 다른 최신 라이브러리(Spring Boot, Feign 등)가 의존하는 Jackson 버전이 충돌하여 `NoSuchFieldError` (Jackson 필드 없음) 오류가 발생했어요.
다음과 같이 개선 작업을 진행했어요.
1.  **AWS SDK v2 마이그레이션**:
*   오래된 `spring-cloud-starter-aws` 의존성을 제거했습니다.
*   `build.gradle`에 AWS SDK v2 BOM 및 필요한 `s3` 모듈 의존성을 추가하여 최신 SDK를 사용하도록 변경했습니다.
2.  **관련 코드 수정**:
*   `AwsConfig.java`를 AWS SDK v2의 `S3Client`, `S3Presigner` 빈을 생성하도록 수정했습니다.
*   `S3Service.java`에서 AWS SDK v1 API 대신 SDK v2 API (`S3Client`, `S3Presigner` 사용)를 사용하도록 Pre-signed URL 생성 및 객체 삭제 로직 등을 수정했습니다.
작업 내용은 다음과 같아요.
1.  `build.gradle` 의존성 수정 (SDK v1 제거, SDK v2 BOM 및 …
> [Fix] AWS SDK v2 마이그레이션 (#548)

- src/main/java/org/sopt/app/application/app_service/AppServiceName.java
- src/main/java/org/sopt/app/application/app_service/AppServiceService.java
- src/main/java/org/sopt/app/application/app_service/OperationConfigService.java
- src/main/java/org/sopt/app/common/config/OperationConfig.java
- src/main/java/org/sopt/app/common/config/OperationConfigCategory.java
- src/main/java/org/sopt/app/common/config/OperationConfigType.java
- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/interfaces/postgres/AppServiceRepository.java
- src/main/java/org/sopt/app/interfaces/postgres/OperationConfigRepository.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- src/main/java/org/sopt/app/presentation/home/response/FloatingButtonResponse.java
- closes #551 
- 운영에 관련된 정보들을 담을 테이블인 `OperationConfig`를 추가했어요.
- 어떤 뷰(기능)에서 쓰이는 지 명시할 `operationConfigCategory`와 해당 값의 타입을 명시할 `operationConfigType` 을 포함했어요.
- 변수명에 해당하는 `key`와 사용처인 `operationConfigCategory`와 같은 값은 DB에 존재할 수 없도록 제약 조건을 추가했어요.
- 예를 들어, 플로팅 버튼에 들어가는 제목을 해당 테이블에 추가한다고 가정할게요. 그렇다면 아래와 같이 구성하면 돼요.
-  `operationConfigCategory`는 `FLOATING_BUTTON`
-  `operationConfigType`은 `TEXT`
-  `key`는 `title`
- `value`는 `플로팅 버튼 이름`
```java
// OperationConfig
@Table(name = "operation_configs" ,
uniqueConstraints = {
@UniqueConstraint(
name = "uk_operation_config_category_key",
columnNames = {"operation_config_category", "key"}
)
})
public class OperationConfig extends BaseEntity {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
@Column(nullable = false)
private …
```
> [Feat] 플로팅 버튼 정보 조회 api 추가 (#551)

- src/main/java/org/sopt/app/common/config/OperationConfigCategory.java
- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- src/main/java/org/sopt/app/presentation/home/response/ReviewFormResponse.java
- closes #553 
- 영재님이 만드신 운영관련 테이블 양식에 맞춰 비슷한 방식으로 후기 작성 관련 정보들을 조회하도록 api를 구현했습니다.
- 노출여부 : 솝커톤은 활동기수, 비활동기수 모두 참여 가능하므르 노출 여부는 회원 여부에 따라서만 결정하도록 했습니다. 회원인 경우 노출, 비회원인 경우 비노출하도록 isActive 필드를 내려줍니다.
로컬 테스트인 관계로 비회원, 즉 isActive false인 경우로 테스트했습니다.
머지 후 db에 관련 데이터 추가해두겠습니다!
> [FEAT] 솝커톤 후기 작성 api 구현 - #553

- src/main/java/org/sopt/app/application/playground/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/application/playground/dto/PlaygroundRecentPost.java
- src/main/java/org/sopt/app/application/playground/dto/PlaygroundRecentPostsResponse.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- src/main/java/org/sopt/app/presentation/home/HomeController.java
- closes #558 
- /api/v1/community/posts/latest internal API 연동 (PlaygroundClient)
- PlaygroundRecentPost, PlaygroundRecentPostsResponse DTO 생성 및 매핑
- HomeController /api/v2/user/posts/latest 엔드포인트 추가
- 게시물 createdAt 기준 분기 로직은 미구현 상태 (기획 요구사항 확인 후 후속 작업 예정)
> [FEAT] 홈화면 플레이그라운드 최신 게시물 목록 조회 api 구현 - #558

- src/main/java/org/sopt/app/application/playground/dto/PlaygroundPopularPost.java
- src/main/java/org/sopt/app/application/playground/dto/PlaygroundRecentPost.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- closes #566 
기획 요구사항에 맞춰 홈 플그 게시물 관련 api의 dto에 userId 필드를 추가했습니다.
> [FEAT] #566 - 홈 플그 게시물 관련 api의 dto 필드 추가

- src/main/java/org/sopt/app/application/app_service/AppServiceName.java
- src/main/java/org/sopt/app/application/playground/PlaygroundClient.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
- closes #568 
- 이전에는 `@HeaderMap`을 통해 직접 전달되던 `Content-Type: application/json` 헤더가 누락되어, 서버에서 `415 Unsupported Media Type` 에러 발생
- `PlaygroundClient.getPlaygroundUserIdsByCondition(...)` 메서드에 `@Headers("Content-Type: application/json")` 애너테이션 추가
- 빈 filters 등 직렬화 문제 없는 것 확인 (JacksonEncoder 적용됨)
- 관련 설정: `ClientConfig.java`에서 JacksonEncoder 이미 적용된 것 확인
- `getReviewFormInfo(Long userId)` 메서드에 서버 기반의 `isActive` 활성화 로직 적용
- 기존 `getFloatingButtonInfo(...)`와 동일한 방식으로:
- `userId` 유효성 확인 후
- `platformService.getStatus(...)` 호출하여 유저 상태 확인
- `AppServiceService`에서 `REVIEW_FORM` 기준의 활성/비활성 상태 조회
- `AppServiceName.REVIEW_FORM` (`serviceName = "REVIEW_FORM"`) 값 사용
> [FIX] #568 - Feign POST 요청 누락된 Content-Type 헤더 추가 및 후기폼 서버드리븐 isActive 활성화 로직 추가

- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/common/security/config/WebSecurityConfig.java
- src/main/java/org/sopt/app/facade/UserFacade.java
- src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
- closes #593 
x
1. 선행작업 완료해준 재헌님께서 PR에서도 작성해주신 부분이긴한데, `create.sql`로 테이블 생성 시 안맞는 부분들이 조금 있었어서 해당 부분은 조금씩 수정하면서 테스트 진행했습니다
2. `DELETE` 메소드의 응답 `HTTP` 코드는 204가 원칙인걸로 알고있긴하지만, 컨벤션으로 200으로 통일된거같아, 다른 `API`들이랑 동일하게 `HttpStatus.OK`로 반환해주었습니다
3. 존재하지 않는 유저의 삭제 요청에 대한 예외처리를 어디 비즈니스 로직에서 진행해줄지도 고민이 많이 됐었는데, 최대한 기존에 구현되어 있었던 컨벤션에 맞춰서 `UserService`단에서 던져주도록 하였습니다
4. 간단한 작업이긴 했으나, 첫 PR이라 컨벤션 관련한 부분은 꼼꼼하게 봐주시면 감사하겠습니다 🙇🏻‍♂️
> [Feat] #593 - 플그관련 default 유저 삭제 Internal api 구현

- src/main/java/org/sopt/app/application/rank/SoptampUserRankCalculator.java
- closes #616 
- 솝탬프 계산 로직에서 userId를 비교하도록 수정. 기존에는 SoptampUser의 id를 사용하여 오류 발생
> [fix] #616 - 솝탬프 순위 계산 로직 수정

- src/main/java/org/sopt/app/application/app_service/SoptampBadgeManager.java
- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
- src/main/java/org/sopt/app/application/rank/CachedUserInfo.java
- src/main/java/org/sopt/app/application/rank/RankScheduler.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserInfo.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
- src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
- src/main/java/org/sopt/app/domain/enums/PlaygroundPart.java
- src/main/java/org/sopt/app/domain/enums/SoptPart.java
- src/main/java/org/sopt/app/presentation/user/UserController.java
- src/main/java/org/sopt/app/presentation/user/UserResponse.java
- closes #619 
- SoptampUser 의 Android 파트의 파트명 prefix 를 '안드로이드' 에서 '안드'로 사용하도록 수정했습니다.
- 기존 iOS 를 처리하시는 부분을 하드코딩으로 처리하신 이유가 이전에는 Playground 에서 제공하던 파트명을 현재는 플랫폼에서 제공해주기 때문에 그렇게 하신 것 같은데, 제가 명세서를 확인해보니 내려주는 값들은 비슷해서 하드코딩 보단 Enum이 낫겠다고 생각해서 PlaygroundPart 를 사용하도록 수정했습니다. 그런데 이 플랫폼 측에서 전달받은 데이터를 PlaygroundPart enum 으로 처리한다면 추후 혼란이 있을 수 있을 것 같은데 enum 명을 수정하는게 좋을까요??
> [fix] #619 - SoptampUser 의 안드로이드 파트명 prefix 수정
