sopt-makers/sopt-backend

- app/src/main/java/org/sopt/app/domain/entity/Alert.java
- app/src/main/java/org/sopt/app/domain/entity/Notice.java
> 컬럼 타입 변경 및 추가 

- app/src/main/java/org/sopt/app/application/alert/AlertService.java
- app/src/main/java/org/sopt/app/application/notice/NoticeService.java
- app/src/main/java/org/sopt/app/interfaces/alert/AlertRepository.java
- app/src/main/java/org/sopt/app/interfaces/notice/NoticeRepository.java
- app/src/main/java/org/sopt/app/presentation/alert/AlertController.java
- app/src/main/java/org/sopt/app/presentation/notice/NoticeController.java
Controleller ,Service, Repository 파일 생성 및 패키지 구조 변경
> Controleller ,Service, Repository 파일 생성 및 패키지 구조 변경

- app/src/main/java/org/sopt/app/application/notice/NoticeService.java
- app/src/main/java/org/sopt/app/domain/entity/BaseEntity.java
- app/src/main/java/org/sopt/app/domain/entity/Notice.java
- app/src/main/java/org/sopt/app/presentation/notice/BaseController.java
- app/src/main/java/org/sopt/app/presentation/notice/NoticeController.java
- app/src/main/resources/application-local.yml
> 공지사항 조회 기능 및  검색

- app/.gitignore
- app/build.gradle
- app/src/main/java/org/sopt/app/common/ResponseCode.java
- app/src/main/java/org/sopt/app/common/exception/ApiException.java
- app/src/main/java/org/sopt/app/common/s3/S3Service.java
- app/src/main/java/org/sopt/app/presentation/notice/NoticeController.java
- app/src/main/java/org/sopt/app/presentation/notice/dto/NoticeRequestDTO.java
- app/src/main/resources/application-local.yml
>  S3 사진업로드 기능

- app/src/main/java/org/sopt/app/AppApplication.java
- app/src/main/java/org/sopt/app/application/notice/NoticeService.java
- app/src/main/java/org/sopt/app/common/constants/Constants.java
- app/src/main/java/org/sopt/app/domain/entity/BaseEntity.java
- app/src/main/java/org/sopt/app/domain/entity/Notice.java
- app/src/main/java/org/sopt/app/presentation/notice/BaseController.java
- app/src/main/java/org/sopt/app/presentation/notice/NoticeController.java
> 공지 업로드 기능 완성 

- app/src/main/java/org/sopt/app/application/alert/AlertService.java
- app/src/main/java/org/sopt/app/domain/enums/Parts.java
- app/src/main/java/org/sopt/app/presentation/alert/AlertController.java
- app/src/main/java/org/sopt/app/presentation/alert/dto/PartRspDTO.java
> 파트 목록 조회하기 API 완성

- app/src/main/java/org/sopt/app/application/alert/AlertService.java
- app/src/main/java/org/sopt/app/application/alert/AlertUseCase.java
- app/src/main/java/org/sopt/app/application/alert/command/SaveAlertCommand.java
- app/src/main/java/org/sopt/app/domain/entity/Alert.java
- app/src/main/java/org/sopt/app/domain/enums/Parts.java
- app/src/main/java/org/sopt/app/interfaces/postgres/alert/AlertRepository.java
- app/src/main/java/org/sopt/app/presentation/alert/AlertController.java
- app/src/main/java/org/sopt/app/presentation/alert/dto/FindUserPartResponseDTO.java
- app/src/main/java/org/sopt/app/presentation/alert/dto/SavePartsRequestDTO.java
1. 마이페이지 > 사용자 알림 목록 조회 API 추가
2. Alert테이블에서 topic 목록을 가져오기 위해 @getter 추가
3. Parts enum 값 목록을 가져오는 코드를 Enum class 내부의 static 메서드로 이동 
- 기존 findPart() 메서드 안에 있는 코드 삭제 필요
> [Feat] 사용자 푸시알림 목록조회

- app/src/main/java/org/sopt/app/application/alert/AlertService.java
> 파트 불러오는 방식 변경

- app/src/main/java/org/sopt/app/application/user/UserService.java
- app/src/main/java/org/sopt/app/common/ResponseCode.java
- app/src/main/java/org/sopt/app/presentation/notice/NoticeController.java
> [FEAT] 공지사항 User의 권한에 따라 조회.

- src/main/java/org/sopt/app/application/mission/MissionService.java
- src/main/java/org/sopt/app/domain/entity/Stamp.java
- src/main/java/org/sopt/app/interfaces/postgres/MissionRepository.java
- src/main/java/org/sopt/app/interfaces/postgres/StampRepository.java
- src/main/java/org/sopt/app/presentation/mission/MissionController.java
- src/main/java/org/sopt/app/presentation/mission/dto/MissionRequestDto.java
- src/main/java/org/sopt/app/presentation/mission/dto/MissionResponseDto.java
> [Feat] Mission 개발 완료 반영 

- src/main/resources/database/create.sql
> Mission 컬럼 타입 수정

- src/main/java/org/sopt/app/application/rank/RankService.java
- src/main/java/org/sopt/app/application/stamp/StampService.java
- src/main/java/org/sopt/app/domain/entity/User.java
- src/main/java/org/sopt/app/presentation/rank/RankController.java
- src/main/java/org/sopt/app/presentation/rank/dto/UserProfileRequestDto.java
Stamp 등록 삭제 시 점수 update,  한마디 편집 Api 추가
> Stamp 등록 삭제 시 점수 update,  한마디 편집 Api 추가

- src/main/java/org/sopt/app/domain/entity/BaseEntity.java
1. API 에서 내려주는 날짜 타입을 yyyy-MM-dd로 일괄 공통 적용
> feat: 날짜 타입을 yyyy-MM-dd로 변경

- src/main/java/org/sopt/app/application/rank/RankService.java
- src/main/java/org/sopt/app/presentation/rank/RankController.java
- src/main/java/org/sopt/app/presentation/rank/dto/RankResponseDto.java
> feat: 랭킹 목록 조회 추가

- src/main/java/org/sopt/app/application/rank/RankService.java
- src/main/java/org/sopt/app/presentation/rank/RankController.java
- src/main/java/org/sopt/app/presentation/rank/dto/FindAllRanksResponseDto.java
- src/main/java/org/sopt/app/presentation/rank/dto/FindRankResponseDto.java
> feat: 랭킹 상세조회 API 추가

- src/main/java/org/sopt/app/application/user/service/UserService.java
- src/main/java/org/sopt/app/domain/entity/User.java
- 랭킹 목록 조회 시 500 에러가 발생하는 이슈
- 회원가입 시 랭킹 점수를 추가하는 point 파라미터 default 값이 설정되어있지 않아 발생한 문제
1 . user 정보 저장 시 point 0L로 defatul 설정
2. 불필요한 주석 제거 및 lint 맞춤
> feat: 회원가입 시 default point 0으로 설정

- src/main/java/org/sopt/app/presentation/auth/AuthController.java
- src/main/java/org/sopt/app/presentation/auth/dto/ChangeNicknameRequestDto.java
> [Fix] 닉네임 변경 시 json 형식 그대로 값이 담기는 현상 수정

- src/main/java/org/sopt/app/application/auth/AuthUseCaseImpl.java
- src/main/java/org/sopt/app/common/exception/DbException.java
- src/main/java/org/sopt/app/presentation/auth/AuthController.java
> feat: 탈퇴하기 API

- src/main/java/org/sopt/app/application/user/dto/SignUpUserDto.java
- src/main/java/org/sopt/app/presentation/auth/AuthController.java
- src/main/java/org/sopt/app/presentation/auth/dto/ChangePasswordRequestDto.java
비밀번호를 string으로 받고 있어서 json 배열로 비밀번호가 수정되는 문제 해결
dto로 받도록 수정
> refactor: 비밀번호 변경 API 수정

- src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
- src/main/java/org/sopt/app/presentation/firebase/dto/FirebaseResponseDto.java
> firebase 연동을 위한 api 추가

- src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
- src/main/java/org/sopt/app/presentation/firebase/dto/FirebaseResponseDto.java
> [Fix] FirebaseResponse 수정

- README.md
1. 솝탬프 프로젝트 readme 문서 작성
- 프로젝트 목적 및 배너 이미지
- local 프로젝트 실행 정보
- wiki에 유스케이스 문서 추가
더 추가적으로 필요한 정보가 있으면 코멘트로 남겨주세요~! 🥸
> [APP-37] docs: 솝탬프 readme.md 작성

- build.gradle
- src/main/java/org/sopt/app/application/auth/JwtTokenService.java
- src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/common/config/JwtExceptionFilter.java
- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
- src/main/java/org/sopt/app/presentation/auth/AuthController.java
- src/main/java/org/sopt/app/presentation/auth/AuthResponse.java
- src/main/java/org/sopt/app/presentation/auth/AuthResponseMapper.java
- src/main/java/org/sopt/app/presentation/user/UserController.java
- src/main/java/org/sopt/app/presentation/user/UserResponse.java
- src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
이전 PR들에서 작성해주신 코드리뷰 토대로 반영하지 못했던 내용들 일괄 반영했습니다.
인증 관련 회의 결과, 프론트도 플레이그라운드 토큰을 가질 수 있게 되어 DTO에 플그 토큰을 추가했습니다.
클라이언트 작업을 위해 메인뷰 DTO 하드코딩하여 제공했으며, 추후 플레이그라운드와 운영팀 API 연동할 예정입니다.
refactor/auth
#47
> refactor: auth

- src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/operation/OperationService.java
- src/main/java/org/sopt/app/application/rank/RankService.java
- src/main/java/org/sopt/app/common/response/ErrorCode.java
- src/main/java/org/sopt/app/presentation/auth/AuthController.java
- src/main/java/org/sopt/app/presentation/auth/AuthRequest.java
- src/main/java/org/sopt/app/presentation/auth/AuthResponse.java
- src/main/java/org/sopt/app/presentation/config/ConfigController.java
- src/main/java/org/sopt/app/presentation/config/ConfigResponse.java
- src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
- src/main/java/org/sopt/app/presentation/mission/MissionController.java
- src/main/java/org/sopt/app/presentation/mission/MissionRequest.java
- src/main/java/org/sopt/app/presentation/mission/MissionResponse.java
- src/main/java/org/sopt/app/presentation/mission/MissionResponseMapper.java
- src/main/java/org/sopt/app/presentation/rank/RankController.java
- src/main/java/org/sopt/app/presentation/rank/RankRequest.java
- src/main/java/org/sopt/app/presentation/rank/RankResponse.java
- src/main/java/org/sopt/app/presentation/rank/RankResponseMapper.java
- src/main/java/org/sopt/app/presentation/s3/S3Controller.java
- src/main/java/org/sopt/app/presentation/s3/S3Response.java
- src/main/java/org/sopt/app/presentation/stamp/StampController.java
- src/main/java/org/sopt/app/presentation/stamp/StampRequest.java
- src/main/java/org/sopt/app/presentation/stamp/StampResponse.java
- src/main/java/org/sopt/app/presentation/stamp/StampResponseMapper.java
- src/main/java/org/sopt/app/presentation/user/UserController.java
- src/main/java/org/sopt/app/presentation/user/UserOriginalController.java
- src/main/java/org/sopt/app/presentation/user/UserRequest.java
- src/main/java/org/sopt/app/presentation/user/UserResponse.java
- src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
- src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
전반적인 리스폰스 처리했습니다.
놓쳤던 미발견 에러들을 전부 처리했고, DTO로 감싸지지 않은 리스폰스를 감쌌습니다.
그 외의 변동사항은 전부 swagger 설명입니다...
feature/error
#61
> feat: Response

- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/domain/entity/User.java
- src/main/java/org/sopt/app/presentation/auth/AuthController.java
- src/main/java/org/sopt/app/presentation/auth/AuthRequest.java
pushToken 로그인 시 저장
feature/pushToken
#73
> feat: pushToken 로그인 시 저장

- src/main/java/org/sopt/app/application/mission/MissionService.java
- src/main/java/org/sopt/app/interfaces/postgres/MissionRepository.java
mission의 display 속성이 반영되지 않던 문제 수정
feat/#80-active-user-ranking
#80
> refactor: mission의 display 속성 반영

- src/main/java/org/sopt/app/presentation/description/DescriptionController.java
swagger description 문구 수정
feat/#83-main-description-api
#83
> fix: swagger description 수정

- src/main/java/org/sopt/app/presentation/stamp/StampController.java
deprecated된 legacy에도 변경 사항 반영
feat/#80-active-user-ranking
registerStampDeprecated메소드 변경
#80
> fix: 스탬프 등록 deprecated 변경 반영 #80

- src/main/java/org/sopt/app/application/stamp/StampFacade.java
- src/main/java/org/sopt/app/application/stamp/StampService.java
- src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
- src/main/java/org/sopt/app/presentation/stamp/StampController.java
- src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
stampController에서 facade 일부 적용 -> 향후 리팩토링으로 전부 적용 예정
> fix: soptamp missionRequest 수정

- src/main/java/org/sopt/app/application/mission/MissionService.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
- src/main/java/org/sopt/app/interfaces/postgres/MissionRepository.java
> fix: current ranking 수정

- src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
- src/main/java/org/sopt/app/presentation/auth/AppAuthController.java
> fix: soptamp user hotfix

- src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
- src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
현재 기수 유저가 아닌 사람이 인증했을 시 토탈 포인트 적립 및 현재 랭킹에 반영 x
> fix: soptampPoint 로직 변경

- src/main/java/org/sopt/app/presentation/rank/RankController.java
> fix: ranking 조회 로직 수정

- src/main/java/org/sopt/app/presentation/stamp/StampController.java
> fix: 스탬프 조회하기 수정

- src/main/java/org/sopt/app/application/stamp/StampFacade.java
> fix: 스탬프 삭제하기 로직 수정

- src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
> fix: 비활동 기수 스탬프 삭제 로직 추가

- src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
- src/main/java/org/sopt/app/application/stamp/StampFacade.java
> hotfix/비활동 기수 스탬프 삭제 로직 수정

- src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
> fix: 오타 수정

- src/main/java/org/sopt/app/application/soptamp/SoptampPointService.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
> hotfix/오타 수정

- src/main/java/org/sopt/app/application/notification/PushTokenService.java
> FIX : 알림서버 등록 시 DB 내 해당 토큰 잔존 여부 검사 제거

- src/main/java/org/sopt/app/domain/entity/Notification.java
Entity 저장시간 timezone KCT로 변경
#118
> FIX : 알림 저장시간 timezone 한국시간대로 수정

- src/main/java/org/sopt/app/application/notification/NotificationService.java
- src/main/java/org/sopt/app/presentation/user/UserResponse.java
- src/main/java/org/sopt/app/presentation/user/UserResponseMapper.java
> HOTFIX : MainView Response Field 이름 변경 및 `isAllConfirm` 의미에 맞는 연산으로 수정

- src/main/java/org/sopt/app/application/auth/PlaygroundAuthService.java
- src/main/java/org/sopt/app/application/user/UserService.java
- src/main/java/org/sopt/app/facade/AuthFacade.java
pg 토큰 갱신 후 저장 로직 추가
hotfix/pg-token-save
#137
> feat: pg 토큰 갱신 시 pg 토큰 저장

- .github/workflows/release-dev-code_deploy.yml
- .github/workflows/release-dev-ssh.yml
> FIX : Add Ignoring Lifecycle stop failure

- src/main/java/org/sopt/app/application/notification/PushTokenService.java
- src/main/java/org/sopt/app/presentation/user/UserPushTokenController.java
- src/main/java/org/sopt/app/presentation/user/UserWithdrawController.java
현재 존재하지 않는 토큰에 대한 삭제요청으로 인한 문제 발생 해결
hotfix/push-token-delete-fix
> Hotfix-push token delete 변경

- src/main/java/org/sopt/app/application/poke/PokeInfo.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/presentation/poke/PokeController.java
- src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
> FIX : 클라이언트 Response DTO 형식 수정 요청 반영

- src/main/java/org/sopt/app/domain/enums/PokeMessageType.java
> FIX : 기획 요구사항에 따른 `PokeMessageType` 정정

- src/main/java/org/sopt/app/application/poke/FriendService.java
> fix: friend 저장 오류 수정

- src/main/java/org/sopt/app/facade/PokeFacade.java
> fix: 친구가 아직 없을 때 빈 값 리턴

- src/main/java/org/sopt/app/application/poke/FriendService.java
- src/main/java/org/sopt/app/application/poke/PokeInfo.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendCustomRepository.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
- src/main/java/org/sopt/app/interfaces/postgres/PokeHistoryRepository.java
- src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
> fix: pgId 추가 및 isAlreadyPoke 변경

- src/main/java/org/sopt/app/application/poke/PokeService.java
> fix: poke isReply 방식 변경

- src/main/java/org/sopt/app/domain/enums/Friendship.java
친한 친구 기준이 2부터라 친구리스트에 새로운 친구가 잡히지 않고 있어서 lower limit을 수정합니다.
> fix: 친구 기준 변경

- src/main/java/org/sopt/app/application/poke/PokeMessageService.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/interfaces/postgres/PokeMessageRepository.java
> fix: pokeMessage Facade 변경

- src/main/java/org/sopt/app/presentation/poke/PokeController.java
- src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
FriendList Response에 totalSize 추가.
FriendList에 응답값의 type으로 Integer wrapper class로 선언되어 있는 것을 수정.(특별히 wrapper class 사용처가 없으므로)
> fix: friendList Response에 totalSize 추가

- src/main/java/org/sopt/app/application/poke/FriendService.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
friendList에 page내부 사이즈 갯수로 잘못 내리는 부분 수정
> fix: pageSize 관계없이 항상 전체 크기 반환

- src/main/java/org/sopt/app/application/poke/FriendService.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
내가 찌를 수 있는 친구가 존재하지 않는 경우 가장 처음 친구 한 명 disable 처리로 넣기
> fix: Friend 응답 디폴트 값 수정

- src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
- src/main/java/org/sopt/app/common/response/ErrorCode.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
> fix: 이미 찌른 경우 에러 처리

- src/main/java/org/sopt/app/facade/PokeFacade.java
user profile image에 대하여 null과 빈스트링으로 들어오는 문제 빈스트링으로 통일
> fix: user profileImage 빈스트링 처리

- src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
- src/main/java/org/sopt/app/facade/PokeFacade.java
- src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
totalPageSize를 pageanation이 사용되는 모든 곳에 추가
> fix: totalPageSize response 추가

- src/main/java/org/sopt/app/application/poke/FriendService.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendRepository.java
> fix: 친구를 찔러보세요 - 친구 관계 변경 로직 대응

- src/main/java/org/sopt/app/application/poke/PokeHistoryService.java
- src/main/java/org/sopt/app/presentation/poke/PokeController.java
> fix: 새로운 유저 판별 로직 수정

- src/main/java/org/sopt/app/application/poke/FriendService.java
> fix: 친구 여부 로직 수정

- src/main/java/org/sopt/app/presentation/poke/PokeController.java
> fix: Controller 오타 수정

- src/main/java/org/sopt/app/application/poke/FriendService.java
- src/main/java/org/sopt/app/interfaces/postgres/FriendRepositoryImpl.java
> fix: 친구 없을 때 에러 대응 및 친구의 친구 로직 수정

- src/main/java/org/sopt/app/domain/enums/Friendship.java
> fix: 친구 관계 숫자 범위 수정

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
이슈 템플릿과 PR 템플릿을 변경했습니다.
closed #322
> docs: 이슈 템플릿과 PR 템플릿 변경

- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> [FIX] cors 구성 빈등록 (#351)

- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> [FIX] Cors 처리 (#351)

- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> [FIX] cors (#351)

- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
> [FIX] cors 제거 (#351)

- build.gradle
- src/main/java/org/sopt/app/common/config/ClientConfig.java
- src/main/java/org/sopt/app/common/config/RestTemplateConfig.java
> [FIX]  api 반복요청 수정 - #362

- src/main/java/org/sopt/app/common/config/ServletRequestWrapperFilter.java
- src/main/java/org/sopt/app/presentation/firebase/FirebaseController.java
> [FIX] Url Match Filter 등록 (#364)

- src/main/java/org/sopt/app/application/fortune/FortuneEventListener.java
- src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
> [FIX] fortune 알람 딥링크  수정 (#369)

- src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
> [FIX] 딥링크 수정 (#369)

- build.gradle
- src/main/resources/application.yml
closed #380 
- 설정을 변경하고 싶으신 경우 다음 방법을 따라주세요
- 1. yaml이 저장된 repository에 yaml파일 수정
- 2. application에 actuator/refresh에 마찬가지로 access token을 담아 POST 요청을 보내기
> [CHORE] spring config 구성 등록 (#380)

- src/main/java/org/sopt/app/application/slack/SlackService.java
- src/main/java/org/sopt/app/common/response/SlackMessageGenerator.java
> [REFACTOR] slack 알림 메세지 변경 -#384

- .github/workflows/release-dev-code_deploy.yml
> [FIX] application-local -> application.yml (#387)

- .github/workflows/release-dev-code_deploy.yml
> [FIX] rollback (#387)

- src/main/java/org/sopt/app/application/fortune/FortuneEventListener.java
- src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
- src/main/java/org/sopt/app/application/poke/PokeEventListener.java
> [REFACTOR]  실제 알림 오도록 구현 - #390

- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
Feign을 위한 기본 생성자를 추가하였습니다
#404
> [FIX] Feign을 위한 기본 생성자 추가

- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
- src/test/java/org/sopt/app/application/UserServiceTest.java
- src/test/java/org/sopt/app/facade/AuthFacadeTest.java
> [Fix] Feign 에러 해결

- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
Feign에서 값을 받기 위한 기본 생성자 추가
closed #404
> [FIX] Feign에서 값을 받기 위한 기본 생성자 추가

- src/main/java/org/sopt/app/application/playground/dto/PlaygroundProfileInfo.java
- src/main/java/org/sopt/app/application/poke/PokeMessageService.java
- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
- src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
- src/main/java/org/sopt/app/facade/AuthFacade.java
- src/test/java/org/sopt/app/application/SoptampUserServiceTest.java
- src/test/java/org/sopt/app/common/fixtures/SoptampUserFixture.java
> [FIX] token refresh error

- src/main/java/org/sopt/app/domain/entity/soptamp/SoptampUser.java
> [fix] Enumerate 추가

- src/main/java/org/sopt/app/common/response/GlobalExceptionHandler.java
> [fix] 임시조치 (#414)

- src/main/java/org/sopt/app/common/response/ErrorCode.java
> [FIX] 404 -> 400 Error 반환하게 변경 (#414)

- src/main/java/org/sopt/app/presentation/report/ReportController.java
> [FEAT] 문의 Controller 구현 (#417)

- src/main/java/org/sopt/app/application/soptamp/SoptampUserService.java
솝탬프 유저 업데이트 시 포인트 0으로 초기화 로직을 추가했습니다.
closed #423
> [FIX] 포인트 0으로 초기화 로직 추가

- src/main/java/org/sopt/app/application/friend/FriendRecommender.java
- src/main/java/org/sopt/app/presentation/poke/PokeResponse.java
플레이그라운드아이디가 유효하지 않은 친구 추천시 에러가 발생하는 오류를 해결했습니다.
closed #449 
- HOTFIX이므로 먼저 머지하도록 하겠습니다. 확인하고 이후 문제 상황 확인되면 말씀해주세요!
> [HOTFIX] 플레이그라운드아이디가 유효하지 않은 친구 추천시 에러 발생 오류 해결

- src/main/java/org/sopt/app/application/meeting/CrewMeetingResponse.java
- src/main/java/org/sopt/app/application/meeting/CrewPart.java
- src/main/java/org/sopt/app/application/meeting/MeetingResponse.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
모든 파트 가져오기 기능에서 joinableParts 필드가 한글로 반환되도록 수정하였습니다.
closed #460
> [MODIFY] 모든 파트 가져오기 기능에서 joinableParts 필드가 한글로 반환되도록 수정

- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
서버 에러 응답값을 500으로 변경하였습니다.
closed #464
> [FIX] /error에 대해 인증없이 접근을 허용하도록 변경

- src/main/java/org/sopt/app/application/fortune/FortuneScheduler.java
main 브랜치에서 매주 월요일에 솝마디 알림이 가도록 변경합니다.
closed #466 
- main 브랜치로 바로 push 하는 PR입니다!
> [MODIFY] 매주 월요일에 솝마디 알림이 가도록 변경

- src/main/java/org/sopt/app/application/calendar/CalendarServiceImpl.java
- src/main/java/org/sopt/app/presentation/calendar/CalendarResponse.java
- src/main/java/org/sopt/app/presentation/calendar/DateFormatter.java
일정 전체 보기에서 반환 형식을 변경했습니다.
closed #473
> [MODIFY] 일정 전체 보기 반환 형식 변경

- src/main/java/org/sopt/app/presentation/home/response/HomeDescriptionResponse.java
메인 문구 조회시 \n을 <br>로 변경
closed #474
> [MODIFY] 메인 문구 조회시 \n을 <br>로 변경

- src/main/java/org/sopt/app/application/app_service/dto/AppServiceEntryStatusResponse.java
- src/main/java/org/sopt/app/common/config/WebSecurityConfig.java
- src/main/java/org/sopt/app/facade/HomeFacade.java
비회원도 앱서비스 조회를 할 수 있도록 변경하였습니다.
closed #485
> [CHORE] 비회원도 앱서비스 조회를 할 수 있도록 변경

- build.gradle
- src/main/resources/application.yml
지속적으로 오류 로그가 발생하는 config 서버를 삭제합니다.
closed #489
> [FIX] config 서버 삭제

- src/main/java/org/sopt/app/domain/entity/User.java
User Entity에 고정된 스키마명을 변경합니다.
closed #493
> [HOTFIX] User Entity에 고정된 스키마명 변경

- .github/workflows/app-cd-dev.yml
prod와 dev가 같은 AWS key를 사용하도록 변경
closed #491
> [MODIFY] prod와 dev가 같은 AWS key를 사용하도록 변경

- .github/workflows/app-cd-dev.yml
> [FIX] script 폴더명 오타 수정

- src/main/java/org/sopt/app/domain/enums/CalendarType.java
- closes #500 
CalendarType에 break, joint_seminar를 추가했습니다.
DB에도 반영 완료했습니다. (Dev에만)
> [Feat] CalendarType 추가

- src/main/java/org/sopt/app/facade/SoptampFacade.java
- closes #535
솝탬프 관련 deleteStamp, report url 로깅 추가했습니다.
> [CHORE] 솝탬프 관련 로깅 추가 - #535

- src/main/java/org/sopt/app/facade/SoptampFacade.java
- closes #535 
fix(SoptampFacade): deleteStamp, report url 로깅 레벨 변경
> [CHORE] 로깅 레벨 변경 - #535

- .github/workflows/app-cd-dev.yml
- Dockerfile
- closes #538 
github secrets의 yml 파일이 정상적으로 반영되지 않는 이슈가 있어 수정을 진행합니다.
- cd pipeline에서 docker build 시 --no-cache 조건 추가
- Dockerfile에서 디버깅을 위해 yml 파일 복사
> [Deploy] docker 배포 관련 수정 - #538

- .github/workflows/app-cd-dev.yml
- closes #538 
--no-cache 옵션을 이전 pr에서 추가했었는데 docker-compose.yml 파일을 못 찾는 이슈가 발생해서 옵션을 다시 제거합니다.
> [DEPLOY] docker build 옵션 변경- #538

- .github/workflows/app-cd-dev.yml
Reverts sopt-makers/sopt-backend#540
> Revert "[DEPLOY] docker build 옵션 변경- #538"

- Dockerfile
Reverts sopt-makers/sopt-backend#539
> Revert "[Deploy] docker 배포 관련 수정 - #538"

- Dockerfile
- closes #538 
Dockerfile 수정 - yml 관련 명령어 추가
> [FIX] Dockerfile 수정 - #538

- src/main/java/org/sopt/app/facade/SoptampFacade.java
- closes #545 
SoptampFacade에 디버깅을 위해 추가했던 로깅 제거했습니다.
> [CHORE] 불필요한 로깅 제거 - #545

- .github/workflows/release-prod.yml
- Dockerfile-prod
- closes #573 
배포 pipeline 관련 수정
> [DEPLOY] #573 - 배포 pipeline 관련 수정

- .github/workflows/release-prod.yml
…buntu/app/로 일치
- closes #572 
- release-prod.yml: scp/ssh 전송/접속 user를 ubuntu로 교정, 경로도 /home/ubuntu/app/로 일치
> [FIX] #573 - prod cd user 및 경로 수정

- script/deploy.sh
- closes #573 
dev/prod 모두 적용가능하도록 deploy.sh 수정
> [DEPLOY] #574 - deploy.sh 수정

- .github/workflows/app-cd-dev.yml
- closes #600 
- ECR 이미지 용량이 부족한 관계로 dev 의 이전 이미지를 자동 삭제되도록 수정했습니다.
> [deploy]  #600 - ECR 이전 이미지 자동 삭제를 위한 workflow 수정

- .github/workflows/app-cd-dev.yml
- closes #602
- 이전 작업에서 시도한 ECR 이전 이미지 자동 삭제를 위한 workflow에서 명령어를 ecr 퍼블릭 레포지토리로 지정하지 않아서 이미지 삭제가 제대로 이뤄지지 않았습니다. 이 부분을 public으로 수정했습니다.
- ECR 퍼블릭은 us-east-1 리전에만 영구적으로 존재하여 리전 명시도 추가했습니다.
> [DEPLOY] #602 - ECR 퍼블릭 레포지토리로 지정 및 region 추가

- .github/workflows/app-cd-dev.yml
- closes #604
- ECR에서 dev 이미지 가져오는 스크립트 수정
- public repository의 경우 이미지를 가져오는 명령어가 달라서 이에 맞춰 수정
> [DEPLOY] #604 - ECR에서 dev 이미지 가져오는 스크립트 수정
